name: Gerar Blacklist

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Rodar o script
        run: python .github/scripts/gerar_blacklist.py

      - name: Upload do arquivo gerado
        uses: actions/upload-artifact@v4
        with:
          name: blacklist
          path: blacklist.txt
